[project]
name = "game-of-life"
version = "0.1.0"
description = "Conway's game of life written in pygame"
authors = [
    { name = "Henrik Petersson", email = "44243358+hnrkcode@users.noreply.github.com" },
]
dependencies = ["pygame>=2.5.2"]
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MIT" }

[tool.pdm.dev-dependencies]
test = ["pytest>=7.4.2", "pytest-cov>=4.1.0"]
lint = ["ruff>=0.1.0", "black>=23.10.0"]

[tool.pdm.scripts]
start = "python run.py"
test = "pytest -v tests/ --cov=gameoflife/"
export = { shell = "pdm export --prod -f requirements > requirements.txt" }
lint = "ruff check ./gameoflife/"
format = "black gameoflife/ tests/"

[tool.ruff]
select = ["E", "F", "B", "I"]
ignore = ["E501"]